name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: vfazano
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23a855f7&color_dots=%230d1117,%237c3aed,%236366f1,%233b82f6,%2322c55e
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23a855f7&color_dots=%230d1117,%237c3aed,%236366f1,%233b82f6,%2322c55e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
